name: ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install project + test deps
        run: |
          python -m pip install -U pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
      - name: Run pytest
        run: pytest -q
