name: ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install project & test deps (pin FastAPI stack)
        run: |
          python -m pip install -U pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip install fastapi==0.95.2 starlette==0.27.0 uvicorn==0.23.2
          python -m pip install -r requirements-dev.txt

      - name: Run pytest
        run: pytest -q
